const langues = [
   {id: 'abk', text: 'Abkhaz', value: false},
   {id: 'ace', text: 'Achinese', value: false},
   {id: 'ach', text: 'Acoli', value: false},
   {id: 'ada', text: 'Adan', value: false},
   {id: 'ady', text: 'Adyghe', value: false},
   {id: 'aar', text: 'Afar', value: false},
   {id: 'afh', text: 'Afrihili', value: false},
   {id: 'afr', text: 'Afrikaans', value: false},
   {id: 'afa', text: 'Afro-asiatiques (diverses)', value: false},
   {id: 'ain', text: 'Ainou', value: false},
   {id: 'aka', text: 'Akan', value: false},
   {id: 'akk', text: 'Akkadien', value: false},
   {id: 'alb', text: 'Albanais', value: false},
   {id: 'ale', text: 'Aleoute', value: false},
   {id: 'alg', text: 'Algonquin', value: false},
   {id: 'ger', text: 'Allemand', value: false},
   {id: 'nds', text: 'allemand (bas) ou saxon (bas)', value: false},
   {id: 'gmh', text: 'Allemand (moyen haut)', value: false},
   {id: 'goh', text: 'Allemand (vieux haut)', value: false},
   {id: 'tut', text: 'Altaiques (autres langues)', value: false},
   {id: 'amh', text: 'Amharique', value: false},
   {id: 'eng', text: 'Anglais', value: false},
   {id: 'enm', text: 'Anglais (moyen)', value: false},
   {id: 'ang', text: 'Anglo-saxon', value: false},
   {id: 'apa', text: 'Apache', value: false},
   {id: 'ara', text: 'Arabe', value: false},
   {id: 'arg', text: 'aragonais', value: false},
   {id: 'arc', text: 'Arameen', value: false},
   {id: 'arp', text: 'Arapaho', value: false},
   {id: 'arn', text: 'Araucan', value: false},
   {id: 'arw', text: 'Arawak', value: false},
   {id: 'arm', text: 'Armenien', value: false},
   {id: 'art', text: 'Artificielles (diverses)', value: false},
   {id: 'asm', text: 'Assamais', value: false},
   {id: 'ast', text: 'Asturien ou Bable', value: false},
   {id: 'ath', text: 'Athapascan', value: false},
   {id: 'aus', text: 'Australian languages', value: false},
   {id: 'ava', text: 'Avar', value: false},
   {id: 'ave', text: 'Avestique', value: false},
   {id: 'awa', text: 'Awadhi', value: false},
   {id: 'aym', text: 'Aymara', value: false},
   {id: 'aze', text: 'Azeri', value: false},
   {id: 'bak', text: 'Bachkir', value: false},
   {id: 'ban', text: 'Balinais', value: false},
   {id: 'bal', text: 'Baloutchi', value: false},
   {id: 'bat', text: 'Baltique', value: false},
   {id: 'bam', text: 'Bambara', value: false},
   {id: 'bai', text: 'Bamileke (diverses)', value: false},
   {id: 'bad', text: 'Banda', value: false},
   {id: 'bnt', text: 'Bantou langues (autre)', value: false},
   {id: 'bas', text: 'Basa', value: false},
   {id: 'baq', text: 'Basque', value: false},
   {id: 'btk', text: 'Batak', value: false},
   {id: 'bej', text: 'Bedja', value: false},
   {id: 'bem', text: 'Bemba', value: false},
   {id: 'ben', text: 'Bengali', value: false},
   {id: 'ber', text: 'Berbere', value: false},
   {id: 'bho', text: 'Bhojpuri', value: false},
   {id: 'bis', text: 'Bislama', value: false},
   {id: 'bel', text: 'Bielorusse', value: false},
   {id: 'bih', text: 'Bihari', value: false},
   {id: 'bik', text: 'Bikol', value: false},
   {id: 'byn', text: 'bilen ou blin', value: false},
   {id: 'bin', text: 'Bini', value: false},
   {id: 'bur', text: 'Birman', value: false},
   {id: 'bla', text: "Blackfoot(= pied noir d'amerique", value: false},
   {id: 'bos', text: 'Bosnian', value: false},
   {id: 'bua', text: 'Buriat', value: false},
   {id: 'bra', text: 'Braj', value: false},
   {id: 'bre', text: 'Breton', value: false},
   {id: 'bug', text: 'Bugi', value: false},
   {id: 'bul', text: 'Bulgare', value: false},
   {id: 'cad', text: 'Caddo', value: false},
   {id: 'car', text: 'Caribe', value: false},
   {id: 'cat', text: 'Catalan', value: false},
   {id: 'cau', text: 'Caucasiennes (diverses)', value: false},
   {id: 'ceb', text: 'Cebuano', value: false},
   {id: 'cel', text: 'Celtiques (langues)', value: false},
   {id: 'cmc', text: 'Chamic langues', value: false},
   {id: 'cha', text: 'Chamorro', value: false},
   {id: 'shn', text: 'chan', value: false},
   {id: 'chr', text: 'Cherokee', value: false},
   {id: 'chy', text: 'Cheyenne', value: false},
   {id: 'chb', text: 'Chibcha', value: false},
   {id: 'chi', text: 'Chinois', value: false},
   {id: 'chn', text: 'Chinook', value: false},
   {id: 'chp', text: 'Chipewyan', value: false},
   {id: 'cho', text: 'Choctaw', value: false},
   {id: 'chk', text: 'chuuk', value: false},
   {id: 'cop', text: 'Copte', value: false},
   {id: 'kor', text: 'Coreen', value: false},
   {id: 'cor', text: 'Cornique', value: false},
   {id: 'cos', text: 'Corse', value: false},
   {id: 'cus', text: 'Couchitique', value: false},
   {id: 'cre', text: 'Cree', value: false},
   {id: 'cpe', text: 'Creoles et pidgins (anglais)', value: false},
   {id: 'crp', text: 'Creoles et pidgins (diverses)', value: false},
   {id: 'cpf', text: 'Creoles et pidgins (francais)', value: false},
   {id: 'cpp', text: 'Creoles et pidgins (portugais)', value: false},
   {id: 'scr', text: 'croate', value: false},
   {id: 'dak', text: 'Dakota', value: false},
   {id: 'dan', text: 'Danois', value: false},
   {id: 'dar', text: 'dargwa', value: false},
   {id: 'day', text: 'Dayak', value: false},
   {id: 'del', text: 'Delaware', value: false},
   {id: 'din', text: 'Dinka', value: false},
   {id: 'dyu', text: 'dioula', value: false},
   {id: 'mis', text: 'Diverses', value: false},
   {id: 'chg', text: 'djaghatai', value: false},
   {id: 'doi', text: 'Dogri', value: false},
   {id: 'dgr', text: 'Dogrib', value: false},
   {id: 'dua', text: 'Douala', value: false},
   {id: 'dra', text: 'Dravidien', value: false},
   {id: 'dzo', text: 'Dzongka', value: false},
   {id: 'sco', text: 'Ecossais', value: false},
   {id: 'efi', text: 'Efik', value: false},
   {id: 'egy', text: 'Egyptien', value: false},
   {id: 'eka', text: 'Ekajuk', value: false},
   {id: 'elx', text: 'Elamite', value: false},
   {id: 'myv', text: 'erza', value: false},
   {id: 'den', text: 'esclave (athapascan)', value: false},
   {id: 'spa', text: 'Espagnol', value: false},
   {id: 'epo', text: 'Esperanto', value: false},
   {id: 'est', text: 'Estonien', value: false},
   {id: 'ewe', text: 'Ewe', value: false},
   {id: 'ewo', text: 'Ewondo', value: false},
   {id: 'fan', text: 'Fang', value: false},
   {id: 'fat', text: 'Fanti', value: false},
   {id: 'fao', text: 'Feroien', value: false},
   {id: 'fij', text: 'Fidjien', value: false},
   {id: 'fil', text: 'filipino ou pilipino', value: false},
   {id: 'fiu', text: 'Finno-ougrien', value: false},
   {id: 'fin', text: 'Finnois', value: false},
   {id: 'fon', text: 'Fon', value: false},
   {id: 'fre', text: 'Francais', value: false},
   {id: 'fro', text: 'Francais (ancien)', value: false},
   {id: 'frm', text: 'Francais (moyen)', value: false},
   {id: 'fur', text: 'Friulian', value: false},
   {id: 'fry', text: 'Frison', value: false},
   {id: 'gaa', text: 'Ga', value: false},
   {id: 'gla', text: 'Gaelique', value: false},
   {id: 'glg', text: 'Galicien', value: false},
   {id: 'orm', text: 'Galla', value: false},
   {id: 'wel', text: 'Gallois', value: false},
   {id: 'lug', text: 'ganda', value: false},
   {id: 'gay', text: 'Gayo', value: false},
   {id: 'gba', text: 'Gbaya', value: false},
   {id: 'geo', text: 'Georgien', value: false},
   {id: 'gem', text: 'Germaniques (diverses)', value: false},
   {id: 'gon', text: 'Gond', value: false},
   {id: 'gor', text: 'Gorontalo', value: false},
   {id: 'got', text: 'Gothique', value: false},
   {id: 'guj', text: 'Gujarati', value: false},
   {id: 'grb', text: 'Grebo', value: false},
   {id: 'grc', text: 'Grec ancien', value: false},
   {id: 'gre', text: 'Grec moderne', value: false},
   {id: 'kal', text: 'groenlandais', value: false},
   {id: 'grn', text: 'Guarani', value: false},
   {id: 'gez', text: 'guèze', value: false},
   {id: 'gwi', text: "Gwich'in", value: false},
   {id: 'hai', text: 'Haida', value: false},
   {id: 'hat', text: 'haitien ou creole haitien', value: false},
   {id: 'hau', text: 'Haoussa', value: false},
   {id: 'haw', text: 'Hawaien', value: false},
   {id: 'heb', text: 'Hebreu', value: false},
   {id: 'her', text: 'Herero', value: false},
   {id: 'hil', text: 'Hiligaynon', value: false},
   {id: 'him', text: 'Himachali', value: false},
   {id: 'hin', text: 'Hindi', value: false},
   {id: 'hmo', text: 'Hiri Motu', value: false},
   {id: 'hit', text: 'Hittite', value: false},
   {id: 'hmn', text: 'Hmong', value: false},
   {id: 'hun', text: 'Hongrois', value: false},
   {id: 'hrv', text: 'République de croatie', value: false},
   {id: 'hup', text: 'Hupa', value: false},
   {id: 'sah', text: 'iakoute', value: false},
   {id: 'iba', text: 'Iban', value: false},
   {id: 'ido', text: 'Ido', value: false},
   {id: 'ibo', text: 'Igbo', value: false},
   {id: 'ijo', text: 'Ijo', value: false},
   {id: 'ilo', text: 'Ilocano', value: false},
   {id: 'und', text: 'Inconnue', value: false},
   {id: 'cai', text: 'Indiennes (langues Amerique Centrale)', value: false},
   {id: 'nai', text: "indiennes d'Amerique du Nord (autres langues)", value: false},
   {id: 'sai', text: 'Indiennes (langues Amerique du sud)', value: false},
   {id: 'inc', text: 'Indo-aryen (groupe)', value: false},
   {id: 'ine', text: 'Indo-europeen (groupe)', value: false},
   {id: 'ind', text: 'Indonesien', value: false},
   {id: 'inh', text: 'Ingouche', value: false},
   {id: 'ina', text: 'Interlingua', value: false},
   {id: 'ile', text: 'Interlingue', value: false},
   {id: 'iku', text: 'Inuktitut', value: false},
   {id: 'ipk', text: 'Inupiaq', value: false},
   {id: 'ira', text: 'Iraniennes (diverses)', value: false},
   {id: 'gle', text: 'Irlandais', value: false},
   {id: 'sga', text: 'Irlandais ancien (---1100)', value: false},
   {id: 'mga', text: 'Irlandais moyen (ca. 1100-1500)', value: false},
   {id: 'iro', text: 'Iroquois', value: false},
   {id: 'ice', text: 'Islandais', value: false},
   {id: 'ita', text: 'Italien', value: false},
   {id: 'jpn', text: 'Japonais', value: false},
   {id: 'jav', text: 'Javanais', value: false},
   {id: 'jrb', text: 'Judeo-arabe', value: false},
   {id: 'lad', text: 'judéo-espagnol', value: false},
   {id: 'jpr', text: 'Judeo-persan', value: false},
   {id: 'kbd', text: 'kabardien', value: false},
   {id: 'kab', text: 'Kabyle', value: false},
   {id: 'kac', text: 'Kachin', value: false},
   {id: 'csb', text: 'kachoube', value: false},
   {id: 'xal', text: 'kalmouk', value: false},
   {id: 'kam', text: 'Kamba', value: false},
   {id: 'kan', text: 'Kanara', value: false},
   {id: 'kau', text: 'Kanouri', value: false},
   {id: 'kaa', text: 'Karakalpak', value: false},
   {id: 'krc', text: 'karatchai balkar', value: false},
   {id: 'kar', text: 'Karen', value: false},
   {id: 'kas', text: 'Kasmiri', value: false},
   {id: 'kaw', text: 'Kawi', value: false},
   {id: 'kaz', text: 'Kazakh', value: false},
   {id: 'kha', text: 'Khasi', value: false},
   {id: 'khm', text: 'Khmer', value: false},
   {id: 'khi', text: 'Khoin (langues)', value: false},
   {id: 'kho', text: 'Khotanais', value: false},
   {id: 'kik', text: 'Kikuyu', value: false},
   {id: 'kmb', text: 'Kimbundu', value: false},
   {id: 'kir', text: 'Kirghiz', value: false},
   {id: 'gil', text: 'kiribati', value: false},
   {id: 'tlh', text: 'klingon', value: false},
   {id: 'kom', text: 'Komi', value: false},
   {id: 'kon', text: 'Kongo', value: false},
   {id: 'kok', text: 'Konkani', value: false},
   {id: 'kos', text: 'Kusaie', value: false},
   {id: 'kum', text: 'Kumyk', value: false},
   {id: 'kpe', text: 'Kpele', value: false},
   {id: 'kro', text: 'Kru', value: false},
   {id: 'kur', text: 'Kurde', value: false},
   {id: 'kru', text: 'Kurukh', value: false},
   {id: 'kut', text: 'Kutenai', value: false},
   {id: 'kua', text: 'Kuanyama', value: false},
   {id: 'lah', text: 'Lahnda', value: false},
   {id: 'lam', text: 'Lamba', value: false},
   {id: 'sgn', text: 'Langage gestuel', value: false},
   {id: 'lao', text: 'Lao', value: false},
   {id: 'lat', text: 'Latin', value: false},
   {id: 'lav', text: 'Lette', value: false},
   {id: 'lez', text: 'Lezgian', value: false},
   {id: 'lim', text: 'limbourgeois', value: false},
   {id: 'lin', text: 'Lingala', value: false},
   {id: 'lit', text: 'Lituanien', value: false},
   {id: 'lin', text: 'Lingala', value: false},
   {id: 'lit', text: 'Lituanien', value: false},
   {id: 'jbo', text: 'lojban', value: false},
   {id: 'loz', text: 'Lozi', value: false},
   {id: 'lub', text: 'Louba', value: false},
   {id: 'lua', text: 'Luba-Lulua', value: false},
   {id: 'lui', text: 'Luiseno', value: false},
   {id: 'lun', text: 'Lunda', value: false},
   {id: 'luo', text: 'Luo (Kenya et Tanzanie)', value: false},
   {id: 'lus', text: 'Lushai', value: false},
   {id: 'ltz', text: 'luxembourgeois', value: false},
   {id: 'mac', text: 'Macedonien', value: false},
   {id: 'mad', text: 'Madourais', value: false},
   {id: 'mag', text: 'Magahi', value: false},
   {id: 'mai', text: 'Maithili', value: false},
   {id: 'mak', text: 'Makasar', value: false},
   {id: 'may', text: 'Malais', value: false},
   {id: 'mal', text: 'Malayalam', value: false},
   {id: 'map', text: 'Malayo-polynesien', value: false},
   {id: 'div', text: 'maldivien', value: false},
   {id: 'mlg', text: 'Malgache', value: false},
   {id: 'mlt', text: 'Maltais', value: false},
   {id: 'mdr', text: 'Mandar', value: false},
   {id: 'mnc', text: 'Manchu', value: false},
   {id: 'man', text: 'Mande', value: false},
   {id: 'mni', text: 'Manipuri', value: false},
   {id: 'glv', text: 'Manx new', value: false},
   {id: 'mno', text: 'Manobo', value: false},
   {id: 'mao', text: 'Maori', value: false},
   {id: 'mar', text: 'Marathi', value: false},
   {id: 'chm', text: 'Mari', value: false},
   {id: 'mah', text: 'Marshall', value: false},
   {id: 'mwr', text: 'Marvari', value: false},
   {id: 'mas', text: 'Masai', value: false},
   {id: 'myn', text: 'Maya', value: false},
   {id: 'men', text: 'Mende', value: false},
   {id: 'mic', text: 'Micmac', value: false},
   {id: 'min', text: 'Minangkabao', value: false},
   {id: 'mwl', text: 'mirandais', value: false},
   {id: 'moh', text: 'Mohawk', value: false},
   {id: 'mdf', text: 'moksa', value: false},
   {id: 'mol', text: 'Moldave', value: false},
   {id: 'mkh', text: 'Mon Khmer (diverses)', value: false},
   {id: 'lol', text: 'Mongo', value: false},
   {id: 'mon', text: 'Mongol', value: false},
   {id: 'mos', text: 'Mossi', value: false},
   {id: 'mun', text: 'Mounda', value: false},
   {id: 'mul', text: 'Multilingue', value: false},
   {id: 'mus', text: 'Muskogee', value: false},
   {id: 'nah', text: 'Nahuatl', value: false},
   {id: 'nap', text: 'napolitain', value: false},
   {id: 'nau', text: 'Nauru', value: false},
   {id: 'nav', text: 'Navaho', value: false},
   {id: 'nde', text: 'Ndebele (Zimbabwe)', value: false},
   {id: 'nbl', text: 'Ndebele (Afrique du Sud)', value: false},
   {id: 'ndo', text: 'Ndongo', value: false},
   {id: 'dut', text: 'Neerlandais', value: false},
   {id: 'dum', text: 'Neerlandais (moyen)', value: false},
   {id: 'nep', text: 'Nepalais', value: false},
   {id: 'new', text: 'Newari', value: false},
   {id: 'nwc', text: 'newari classique', value: false},
   {id: 'nia', text: 'Nias', value: false},
   {id: 'nic', text: 'Nigero-congolais', value: false},
   {id: 'ssa', text: 'Nilo-saharien (groupe)', value: false},
   {id: 'niu', text: 'Niuean', value: false},
   {id: 'nog', text: 'nogai ou nogay', value: false},
   {id: 'non', text: 'Norrois vieux', value: false},
   {id: 'nor', text: 'Norvegien', value: false},
   {id: 'nob', text: 'Norvegien Bokmal', value: false},
   {id: 'nno', text: 'Norvegien Nynorsk', value: false},
   {id: 'nub', text: 'Nubien', value: false},
   {id: 'nym', text: 'Nyamwezi', value: false},
   {id: 'nya', text: 'Nyanja', value: false},
   {id: 'nyn', text: 'Nyankole', value: false},
   {id: 'nyo', text: 'Nyoro', value: false},
   {id: 'nzi', text: 'Nzima', value: false},
   {id: 'oci', text: 'Occitan', value: false},
   {id: 'oji', text: 'Ojibwa', value: false},
   {id: 'ori', text: 'Oriya', value: false},
   {id: 'osa', text: 'Osage', value: false},
   {id: 'oss', text: 'Ossete', value: false},
   {id: 'oto', text: 'Otomang', value: false},
   {id: 'udm', text: 'oudmourte', value: false},
   {id: 'uga', text: 'Ougaritique', value: false},
   {id: 'uig', text: 'Ouigour', value: false},
   {id: 'urd', text: 'ourdu', value: false},
   {id: 'uzb', text: 'Ouzbek', value: false},
   {id: 'pus', text: 'Pachto', value: false},
   {id: 'pal', text: 'Pahlavi', value: false},
   {id: 'pau', text: 'Palauan', value: false},
   {id: 'pli', text: 'Pali', value: false},
   {id: 'pam', text: 'Pampanga', value: false},
   {id: 'pag', text: 'Pangasinan', value: false},
   {id: 'pap', text: 'Papiamento', value: false},
   {id: 'paa', text: 'Papou', value: false},
   {id: 'pan', text: 'Penjabi', value: false},
   {id: 'per', text: 'Persan moderne', value: false},
   {id: 'peo', text: 'Perse ancien (600-400 av. J.C.)', value: false},
   {id: 'ful', text: 'peul', value: false},
   {id: 'phn', text: 'Phoenician', value: false},
   {id: 'phi', text: 'Pilipino langues (autre)', value: false},
   {id: 'pon', text: 'Pohnpei', value: false},
   {id: 'pol', text: 'Polonais', value: false},
   {id: 'por', text: 'Portugais', value: false},
   {id: 'pra', text: 'Prakrit', value: false},
   {id: 'pro', text: 'Provencal (avant 1500)', value: false},
   {id: 'que', text: 'Quechua', value: false},
   {id: 'raj', text: 'Rajasthani', value: false},
   {id: 'rap', text: 'Rapanui', value: false},
   {id: 'rar', text: 'Rarotonga', value: false},
   {id: 'roh', text: 'Rhetoroman (groupe)', value: false},
   {id: 'roa', text: 'Romanes (diverses)', value: false},
   {id: 'rum', text: 'Roumain', value: false},
   {id: 'run', text: 'Rundi', value: false},
   {id: 'rus', text: 'Russe', value: false},
   {id: 'kin', text: 'rwanda', value: false},
   {id: 'sal', text: 'Salish (famille)', value: false},
   {id: 'sam', text: 'Samaritain', value: false},
   {id: 'smi', text: 'Sami', value: false},
   {id: 'smi', text: 'ex lapon', value: false},
   {id: 'smn', text: "Sami d'Inari", value: false},
   {id: 'smj', text: 'Sami de Lule', value: false},
   {id: 'sme', text: 'Sami du Nord', value: false},
   {id: 'sma', text: 'Sami du Sud', value: false},
   {id: 'sms', text: 'Sami Skolt', value: false},
   {id: 'smo', text: 'Samoa', value: false},
   {id: 'sad', text: 'Sandawe', value: false},
   {id: 'sag', text: 'Sango', value: false},
   {id: 'san', text: 'Sanskrit', value: false},
   {id: 'sat', text: 'Santali', value: false},
   {id: 'srd', text: 'Sardinian', value: false},
   {id: 'sas', text: 'Sasak', value: false},
   {id: 'sel', text: 'Selkoup', value: false},
   {id: 'sem', text: 'Semitiques (diverses)', value: false},
   {id: 'scc', text: 'Serbe', value: false},
   {id: 'srr', text: 'Serere', value: false},
   {id: 'sna', text: 'Shona', value: false},
   {id: 'scn', text: 'sicilien', value: false},
   {id: 'sid', text: 'Sidamo', value: false},
   {id: 'snd', text: 'Sindhi', value: false},
   {id: 'sin', text: 'Singhalais', value: false},
   {id: 'sit', text: 'Sino-tibetaines (langues)', value: false},
   {id: 'sio', text: 'Siou (famille)', value: false},
   {id: 'sla', text: 'Slaves (diverses)', value: false},
   {id: 'chu', text: "Slavon d'eglise", value: false},
   {id: 'slo', text: 'Slovaque', value: false},
   {id: 'slv', text: 'Slovene', value: false},
   {id: 'sog', text: 'Sogdien', value: false},
   {id: 'som', text: 'Somali', value: false},
   {id: 'son', text: 'Songhai', value: false},
   {id: 'snk', text: 'Soninke', value: false},
   {id: 'dsb', text: 'sorabe (bas)', value: false},
   {id: 'hsb', text: 'sorabe (haut)', value: false},
   {id: 'wen', text: 'sorabes (langues)', value: false},
   {id: 'sot', text: 'Sotho du Sud', value: false},
   {id: 'nso', text: 'Sotho du Nord', value: false},
   {id: 'sun', text: 'Soundanais', value: false},
   {id: 'sus', text: 'Soussou', value: false},
   {id: 'swe', text: 'Suedois', value: false},
   {id: 'suk', text: 'Sukuma', value: false},
   {id: 'sux', text: 'Sumerien', value: false},
   {id: 'swa', text: 'Swahili', value: false},
   {id: 'ssw', text: 'Swazi', value: false},
   {id: 'syr', text: 'Syriaque', value: false},
   {id: 'tgk', text: 'Tadjik', value: false},
   {id: 'tgl', text: 'Tagalog', value: false},
   {id: 'tah', text: 'Tahitien', value: false},
   {id: 'tmh', text: 'Tamashek', value: false},
   {id: 'tam', text: 'Tamoul', value: false},
   {id: 'tat', text: 'Tatar', value: false},
   {id: 'crh', text: 'tatar de Crime', value: false},
   {id: 'cze', text: 'Tcheque', value: false},
   {id: 'che', text: 'Tchetchene', value: false},
   {id: 'chv', text: 'Tchouvache', value: false},
   {id: 'tel', text: 'Telugu', value: false},
   {id: 'tem', text: 'Temne', value: false},
   {id: 'ter', text: 'Tereno', value: false},
   {id: 'tet', text: 'Tetum', value: false},
   {id: 'tha', text: 'Thai', value: false},
   {id: 'tai', text: 'Thai langues (autre)', value: false},
   {id: 'tib', text: 'Tibetain', value: false},
   {id: 'tig', text: 'Tigre', value: false},
   {id: 'tir', text: 'Tigrina', value: false},
   {id: 'tiv', text: 'Tiv', value: false},
   {id: 'tli', text: 'Tlingit', value: false},
   {id: 'tpi', text: 'Tok Pisin', value: false},
   {id: 'tkl', text: 'Tokelau', value: false},
   {id: 'tog', text: 'Tonga', value: false},
   {id: 'ton', text: 'Tonga (polynesien)', value: false},
   {id: 'tyv', text: 'Touva', value: false},
   {id: 'rom', text: 'tsigane', value: false},
   {id: 'tsi', text: 'Tsimshian', value: false},
   {id: 'tso', text: 'Tsonga', value: false},
   {id: 'tsn', text: 'Tswana', value: false},
   {id: 'tum', text: 'Tumbuka', value: false},
   {id: 'tup', text: 'Tupi (langues)', value: false},
   {id: 'tur', text: 'Turc', value: false},
   {id: 'ota', text: 'Turc ottoman (ecriture arabe)', value: false},
   {id: 'tuk', text: 'Turkmene', value: false},
   {id: 'tvl', text: 'Tuvalu', value: false},
   {id: 'twi', text: 'Twi', value: false},
   {id: 'ukr', text: 'Ukrainien', value: false},
   {id: 'umb', text: 'Umbuntu', value: false},
   {id: 'vai', text: 'Vai', value: false},
   {id: 'ven', text: 'Venda', value: false},
   {id: 'vie', text: 'Vietnamien', value: false},
   {id: 'vol', text: 'Volapuk', value: false},
   {id: 'vot', text: 'Vote', value: false},
   {id: 'wak', text: 'Wakash (groupe)', value: false},
   {id: 'wal', text: 'Walamo', value: false},
   {id: 'wln', text: 'Wallon', value: false},
   {id: 'war', text: 'Waray', value: false},
   {id: 'was', text: 'Washo', value: false},
   {id: 'wol', text: 'Wolof', value: false},
   {id: 'xho', text: "X'hosa", value: false},
   {id: 'sah', text: 'Yakut', value: false},
   {id: 'yao', text: 'Yao', value: false},
   {id: 'yap', text: 'Yap', value: false},
   {id: 'iii', text: 'yi de Sichuan', value: false},
   {id: 'yid', text: 'Yiddish', value: false},
   {id: 'yor', text: 'Yoruba', value: false},
   {id: 'ypk', text: 'Yupik langages', value: false},
   {id: 'znd', text: 'Zande', value: false},
   {id: 'zap', text: 'Zapoteque', value: false},
   {id: 'zen', text: 'Zenaga', value: false},
   {id: 'zha', text: 'Zhuang', value: false},
   {id: 'zul', text: 'Zoulou', value: false},
   {id: 'zun', text: 'Zuni', value: false},
];

export default langues;
