const pays = [
  {id: 'AF', text: 'Afghanistan', value: false},
  {id: 'ZA', text: 'Afrique du Sud', value: false},
  {id: 'AX', text: 'Aland Iles', value: false},
  {id: 'AL', text: 'Albanie', value: false},
  {id: 'DZ', text: 'Algérie', value: false},
  {id: 'DE', text: 'Allemagne', value: false},
  {id: 'DD', text: "Allemagne de l'Est", value: false},
  {id: 'AD', text: 'Andorre', value: false},
  {id: 'AO', text: 'Angola', value: false},
  {id: 'AI', text: 'Anguilla', value: false},
  {id: 'AQ', text: 'Antarctique', value: false},
  {id: 'AG', text: 'Antigua et Barbuda', value: false},
  {id: 'AN', text: 'Antilles néerlandaises', value: false},
  {id: 'SA', text: 'Arabie Saoudite', value: false},
  {id: 'AR', text: 'Argentine', value: false},
  {id: 'AM', text: 'Arménie', value: false},
  {id: 'AW', text: 'Aruba', value: false},
  {id: 'AU', text: 'Australie', value: false},
  {id: 'AT', text: 'Autriche', value: false},
  {id: 'AZ', text: 'Azerbaïdjan', value: false},
  {id: 'BS', text: 'Bahamas', value: false},
  {id: 'BH', text: 'Bahrein', value: false},
  {id: 'BD', text: 'Bangladesh', value: false},
  {id: 'BB', text: 'Barbade', value: false},
  {id: 'BY', text: 'Bélarus', value: false},
  {id: 'BE', text: 'Belgique', value: false},
  {id: 'BZ', text: 'Bélize', value: false},
  {id: 'BJ', text: 'Bénin', value: false},
  {id: 'BM', text: 'Bermudes', value: false},
  {id: 'BT', text: 'Bhoutan', value: false},
  {id: 'BO', text: 'Bolivie', value: false},
  {id: 'BA', text: 'Bosnie-Herzégovine', value: false},
  {id: 'BW', text: 'Botswana', value: false},
  {id: 'BV', text: 'Bouvet (Ile)', value: false},
  {id: 'BR', text: 'Brésil', value: false},
  {id: 'BN', text: 'Brunei Darussalam', value: false},
  {id: 'BG', text: 'Bulgarie', value: false},
  {id: 'BF', text: 'Burkina Faso', value: false},
  {id: 'BI', text: 'Burundi', value: false},
  {id: 'KY', text: 'Caïmanes (Iles)', value: false},
  {id: 'KH', text: 'Cambodge', value: false},
  {id: 'CM', text: 'Cameroun', value: false},
  {id: 'CA', text: 'Canada', value: false},
  {id: 'CT', text: 'Canton et Enderbury (Iles)', value: false},
  {id: 'CV', text: 'Cap-Vert', value: false},
  {id: 'CF', text: 'Centrafricaine (République)', value: false},
  {id: 'CL', text: 'Chili', value: false},
  {id: 'CN', text: 'Chine', value: false},
  {id: 'CX', text: 'Christmas (Ile)', value: false},
  {id: 'CY', text: 'Chypre', value: false},
  {id: 'CC', text: 'Cocos (Keeling)(Iles)', value: false},
  {id: 'CO', text: 'Colombie', value: false},
  {id: 'KM', text: 'Comores', value: false},
  {id: 'CG', text: 'Congo', value: false},
  {id: 'CD', text: 'la République démocratique du Congo', value: false},
  {id: 'CK', text: 'Cook (Iles)', value: false},
  {id: 'KR', text: 'République de Corée', value: false},
  {id: 'KP', text: 'République populaire démocratique de Corée', value: false},
  {id: 'CR', text: 'Costa Rica', value: false},
  {id: 'CI', text: "Côte d'Ivoire", value: false},
  {id: 'HR', text: 'Croatie', value: false},
  {id: 'CU', text: 'Cuba', value: false},
  {id: 'DK', text: 'Danemark', value: false},
  {id: 'DJ', text: 'Djibouti', value: false},
  {id: 'DO', text: 'République Dominicaine', value: false},
  {id: 'DM', text: 'Dominique', value: false},
  {id: 'EG', text: 'Egypte', value: false},
  {id: 'SV', text: 'El Salvador', value: false},
  {id: 'AE', text: 'Emirats arabes unis', value: false},
  {id: 'EC', text: 'Equateur', value: false},
  {id: 'ER', text: 'Erythrée', value: false},
  {id: 'ES', text: 'Espagne', value: false},
  {id: 'EE', text: 'Estonie', value: false},
  {id: 'US', text: 'Etats-Unis', value: false},
  {id: 'ET', text: 'Ethiopie', value: false},
  {id: 'FK', text: 'Falkland (Iles) (Malvinas)', value: false},
  {id: 'FO', text: 'Feroe (Iles)', value: false},
  {id: 'FJ', text: 'Fidji', value: false},
  {id: 'FI', text: 'Finlande', value: false},
  {id: 'FR', text: 'France', value: false},
  {id: 'GA', text: 'Gabon', value: false},
  {id: 'GM', text: 'Gambie', value: false},
  {id: 'GE', text: 'Géorgie', value: false},
  {id: 'GS', text: 'Géorgie du sud et les Iles Sandwich du Sud', value: false},
  {id: 'GH', text: 'Ghana', value: false},
  {id: 'GI', text: 'Gibraltar', value: false},
  {id: 'GR', text: 'Grèce', value: false},
  {id: 'GD', text: 'Grenade', value: false},
  {id: 'GL', text: 'Groenland', value: false},
  {id: 'GP', text: 'Guadeloupe', value: false},
  {id: 'GU', text: 'Guam', value: false},
  {id: 'GT', text: 'Guatemala', value: false},
  {id: 'GG', text: 'Guernesey', value: false},
  {id: 'GN', text: 'Guinée', value: false},
  {id: 'GW', text: 'Guinée-Bissau', value: false},
  {id: 'GQ', text: 'Guinée équatoriale', value: false},
  {id: 'GY', text: 'Guyana', value: false},
  {id: 'GF', text: 'Guyane française', value: false},
  {id: 'HT', text: 'Haïti', value: false},
  {id: 'HM', text: 'Heard (Ile) et McDonald (Iles)', value: false},
  {id: 'HN', text: 'Honduras', value: false},
  {id: 'HK', text: 'Hong-Kong', value: false},
  {id: 'HU', text: 'Hongrie', value: false},
  {id: 'IM', text: 'Ile de Man', value: false},
  {id: 'UM', text: 'Iles mineures éloignées des Etats-Unis', value: false},
  {id: 'VG', text: 'Iles vierges britanniques', value: false},
  {id: 'VI', text: 'Iles vierges des Etats-Unis', value: false},
  {id: 'XX', text: 'pays inconnu', value: false},
  {id: 'IN', text: 'Inde', value: false},
  {id: 'ID', text: 'Indonésie', value: false},
  {id: 'IR', text: "République islamique d'Iran", value: false},
  {id: 'IQ', text: 'Iraq', value: false},
  {id: 'IE', text: 'Irlande', value: false},
  {id: 'IS', text: 'Islande', value: false},
  {id: 'IL', text: 'Israël', value: false},
  {id: 'IT', text: 'Italie', value: false},
  {id: 'JM', text: 'Jamaïque', value: false},
  {id: 'JP', text: 'Japon', value: false},
  {id: 'JE', text: 'Jersey', value: false},
  {id: 'JO', text: 'Jordanie', value: false},
  {id: 'KZ', text: 'Kazakhstan', value: false},
  {id: 'KE', text: 'Kenya', value: false},
  {id: 'KG', text: 'Kirghizistan', value: false},
  {id: 'KI', text: 'Kiribati', value: false},
  {id: 'KW', text: 'Koweït', value: false},
  {id: 'LA', text: 'République démocratique populaire du Laos', value: false},
  {id: 'LS', text: 'Lesotho', value: false},
  {id: 'LV', text: 'Lettonie', value: false},
  {id: 'LB', text: 'Liban', value: false},
  {id: 'LR', text: 'Libéria', value: false},
  {id: 'LY', text: 'Libyenne ou Jamahiriya arabe', value: false},
  {id: 'LI', text: 'Liechtenstein', value: false},
  {id: 'LT', text: 'Lituanie', value: false},
  {id: 'LU', text: 'Luxembourg', value: false},
  {id: 'MO', text: 'Macao', value: false},
  {id: 'MK', text: "l'ex-République yougoslave de Macédoine", value: false},
  {id: 'MG', text: 'Madagascar', value: false},
  {id: 'MY', text: 'Malaisie', value: false},
  {id: 'MW', text: 'Malawi', value: false},
  {id: 'MV', text: 'Maldives', value: false},
  {id: 'ML', text: 'Mali', value: false},
  {id: 'MT', text: 'Malte', value: false},
  {id: 'MP', text: 'Mariannes du nord (Iles)', value: false},
  {id: 'MA', text: 'Maroc', value: false},
  {id: 'MH', text: 'Marshall (Iles)', value: false},
  {id: 'MQ', text: 'Martinique', value: false},
  {id: 'MU', text: 'Maurice', value: false},
  {id: 'MR', text: 'Mauritanie', value: false},
  {id: 'YT', text: 'Mayotte', value: false},
  {id: 'MX', text: 'Mexique', value: false},
  {id: 'FM', text: 'Etats fédérés de Micronésie', value: false},
  {id: 'MD', text: 'République de Moldova', value: false},
  {id: 'MC', text: 'Monaco', value: false},
  {id: 'MN', text: 'Mongolie', value: false},
  {id: 'ME', text: 'Monténégro', value: false},
  {id: 'MS', text: 'Montserrat', value: false},
  {id: 'MZ', text: 'Mozambique', value: false},
  {id: 'ZZ', text: 'pays multiples', value: false},
  {id: 'MM', text: 'Myanmar', value: false},
  {id: 'NA', text: 'Namibie', value: false},
  {id: 'NR', text: 'Nauru', value: false},
  {id: 'NP', text: 'Népal', value: false},
  {id: 'NI', text: 'Nicaragua', value: false},
  {id: 'NE', text: 'Niger', value: false},
  {id: 'NG', text: 'Nigéria', value: false},
  {id: 'NU', text: 'Niué', value: false},
  {id: 'NF', text: 'Norfolk (Ile)', value: false},
  {id: 'NO', text: 'Norvège', value: false},
  {id: 'NC', text: 'Nouvelle-Calédonie', value: false},
  {id: 'NZ', text: 'Nouvelle-Zélande', value: false},
  {id: 'IO', text: "Territoire britannique de l'Océan indien", value: false},
  {id: 'OM', text: 'Oman', value: false},
  {id: 'UG', text: 'Ouganda', value: false},
  {id: 'UZ', text: 'Ouzbékistan', value: false},
  {id: 'PK', text: 'Pakistan', value: false},
  {id: 'PW', text: 'Palaos', value: false},
  {id: 'PS', text: 'Territoire Palestinien occupé', value: false},
  {id: 'PA', text: 'Panama', value: false},
  {id: 'PG', text: 'Papouasie-Nouvelle-Guinée', value: false},
  {id: 'PY', text: 'Paraguay', value: false},
  {id: 'NL', text: 'Pays-Bas', value: false},
  {id: 'PE', text: 'Pérou', value: false},
  {id: 'PH', text: 'Philippines', value: false},
  {id: 'PN', text: 'Pitcairn', value: false},
  {id: 'PL', text: 'Pologne', value: false},
  {id: 'PF', text: 'Polynésie française', value: false},
  {id: 'PR', text: 'Porto Rico', value: false},
  {id: 'PT', text: 'Portugal', value: false},
  {id: 'QA', text: 'Qatar', value: false},
  {id: 'RE', text: 'Réunion', value: false},
  {id: 'RO', text: 'Roumanie', value: false},
  {id: 'GB', text: 'Royaume-Uni', value: false},
  {id: 'RU', text: 'Fédération de Russie', value: false},
  {id: 'RW', text: 'Rwanda', value: false},
  {id: 'EH', text: 'Sahara occidental', value: false},
  {id: 'SH', text: 'Sainte-Hélène', value: false},
  {id: 'LC', text: 'Sainte-Lucie', value: false},
  {id: 'KN', text: 'Saint-Kitts-et-Nevis', value: false},
  {id: 'SM', text: 'Saint-Marin', value: false},
  {id: 'PM', text: 'Saint-Pierre-et-Miquelon', value: false},
  {id: 'VA', text: 'Saint-Siège, Etat de la Cité du Vatican', value: false},
  {id: 'VC', text: 'Saint-Vincent-et-les-Grenadines', value: false},
  {id: 'SB', text: 'Salomon (Iles)', value: false},
  {id: 'WS', text: 'Samoa', value: false},
  {id: 'AS', text: 'Samoa américaines', value: false},
  {id: 'ST', text: 'Sao Tomé-et-Principe', value: false},
  {id: 'SN', text: 'Sénégal', value: false},
  {id: 'RS', text: 'Serbie', value: false},
  {id: 'SC', text: 'Seychelles', value: false},
  {id: 'SL', text: 'Sierra Leone', value: false},
  {id: 'SG', text: 'Singapour', value: false},
  {id: 'SK', text: 'Slovaquie', value: false},
  {id: 'SI', text: 'Slovénie', value: false},
  {id: 'SO', text: 'Somalie', value: false},
  {id: 'SD', text: 'Soudan', value: false},
  {id: 'LK', text: 'Sri Lanka', value: false},
  {id: 'SE', text: 'Suède', value: false},
  {id: 'CH', text: 'Suisse', value: false},
  {id: 'SR', text: 'Suriname', value: false},
  {id: 'SJ', text: 'Svalbard et Ile Jan Mayen', value: false},
  {id: 'SZ', text: 'Swaziland', value: false},
  {id: 'SY', text: 'République arabe Syrienne', value: false},
  {id: 'TJ', text: 'Tadjikistan', value: false},
  {id: 'TW', text: 'Taïwan, Province de Chine', value: false},
  {id: 'TZ', text: 'République unie de Tanzanie', value: false},
  {id: 'TD', text: 'Tchad', value: false},
  {id: 'CS', text: 'Tchècoslovaquie', value: false},
  {id: 'CZ', text: 'République Tchèque', value: false},
  {id: 'TF', text: 'Terres australes et antarctiques françaises', value: false},
  {id: 'TH', text: 'Thaïlande', value: false},
  {id: 'TL', text: 'Timor-Leste', value: false},
  {id: 'TG', text: 'Togo', value: false},
  {id: 'TK', text: 'Tokelau', value: false},
  {id: 'TO', text: 'Tonga', value: false},
  {id: 'TT', text: 'Trinité-et-Tobago', value: false},
  {id: 'TN', text: 'Tunisie', value: false},
  {id: 'TM', text: 'Turkménistan', value: false},
  {id: 'TC', text: 'Turks et Caïques (Iles)', value: false},
  {id: 'TR', text: 'Turquie', value: false},
  {id: 'TV', text: 'Tuvalu', value: false},
  {id: 'SU', text: 'U.S.S.R.', value: false},
  {id: 'UA', text: 'Ukraine', value: false},
  {id: 'UY', text: 'Uruguay', value: false},
  {id: 'VU', text: 'Vanuatu', value: false},
  {id: 'VE', text: 'Venezuela', value: false},
  {id: 'VN', text: 'Viet-nam', value: false},
  {id: 'VD', text: 'Viet-nam (Sud)', value: false},
  {id: 'WF', text: 'Wallis et Futuna', value: false},
  {id: 'YE', text: 'Yémen', value: false},
  {id: 'YD', text: 'Yémen (Nord)', value: false},
  {id: 'YU', text: 'Yougoslavie', value: false},
  {id: 'ZR', text: 'Zaïre', value: false},
  {id: 'ZM', text: 'Zambie', value: false},
  {id: 'ZW', text: 'Zimbabwe', value: false},
];

export default pays;
