const pcpMetiers = [
   {key: 'PCAS', text: 'Arts du spectacle'},
   {key: 'PCAM', text: 'Arts-et-Métiers'},
   {key: 'PCBioD', text: 'Biodiversité et écosystème'},
   {key: 'PCChimie', text: 'Chimie'},
   {key: 'PCDroit', text: 'Droit'},
   {key: 'PCEco', text: 'Economie et gestion'},
   {key: 'PCIta', text: 'Etudes italiennes'},
   {key: 'PCEBCO', text: 'Europe balkanique, centrale et orientale'},
   {key: 'PCGeo', text: 'Géographie et urbanisme'},
   {key: 'PCGeoS', text: 'Géosciences'},
   {key: 'PCHistoire', text: 'Histoire'},
   {key: 'PCArt', text: "Histoire de l'Art et muséologie"},
   {key: 'PCGer', text: 'Langues, littératures, civilisation germaniques'},
   {key: 'PCMath', text: 'Mathématiques RNBM'},
   {key: 'PCMed', text: 'Médecine'},
   {key: 'PCPhar', text: 'Pharmacie'},
   {key: 'PCPhilo', text: 'Philosophie'},
   {key: 'PCPhy', text: 'Physique'},
   {key: 'PCPsy', text: 'Psychologie, Psychanalyse'},
   {key: 'PCPol', text: 'Science Politique'},
   {key: 'PCAnt', text: "Sciences de l'Antiquité et Archéologie"},
   {key: 'PCEdu', text: "Sciences de l'éducation"},
   {key: 'PCNum', text: 'Sciences du Numérique'},
   {key: 'PCRel', text: 'Sciences Religieuses'},
   {key: 'PCSTAPS', text: 'STAPS'},
];

export default pcpMetiers;
