const pcpRegions = [
   {key: 'PCAq', text: 'Aquitaine'},
   {key: 'PCAuv', text: 'Auvergne'},
   {key: 'PCBo', text: 'Bourgogne'},
   {key: 'PCBre', text: 'Bretagne'},
   {key: 'PCGE', text: 'Grand Est'},
   {key: 'PCCAPI', text: 'Champagne-Ardenne Picardie'},
   {key: 'PCCor', text: 'Corse'},
   {key: 'PCFC', text: 'Franche-Comté'},
   {key: 'PCLR', text: 'Occitanie-Est'},
   {key: 'PCLim', text: 'Limousin'},
   {key: 'PCMP', text: 'Occitanie-Ouest'},
   {key: 'PCNPDC', text: 'Nord-Pas-de-Calais'},
   {key: 'PCPACA', text: 'Provence-Alpes-Côte d\'Azur'},
   {key: 'PCPL', text: 'Pays de Loire'},
   {key: 'PCPic', text: 'Picardie'},
   {key: 'PCRA', text: 'Rhône-Alpes'},
   {key: 'PCSAM', text: 'Sciences Aix-Marseille'},
   {key: 'PCSCen', text: 'Sciences Centre Val de Loire'},
   {key: 'PCUP', text: 'Université de Poitiers'},
   {key: 'PCUR', text: 'Université de Rouen'},
];
export default pcpRegions;
